---
- name: Install and configure Nginx web server
  hosts: localhost
  become: true
  tasks:
  
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Create a Hello World page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head><title>Hello World</title></head>
            <body><h1>Hello World from Nginx</h1></body>
          </html>
        owner: www-data
        group: www-data
        mode: 0644

