---
- name: Configure Nginx to forward logs to Splunk
  hosts: localhost
  become: true
  tasks:

    - name: Ensure Nginx log format includes IP and User-Agent
      lineinfile:
        path: /etc/nginx/nginx.conf
        insertafter: "http {"
        line: |
          log_format splunk '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

    - name: Restart Nginx to apply log format changes
      systemd:
        name: nginx
        state: restarted

    - name: Configure Splunk input to receive Nginx logs
      shell: |
        docker exec splunk sudo /opt/splunk/bin/splunk add monitor /var/log/nginx/access.log
        docker exec splunk sudo /opt/splunk/bin/splunk restart

