---
- name: Install Splunk on Docker and insert certificate
  hosts: localhost
  become: yes
  tasks:

    - name: Install necessary packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Splunk Docker image
      docker_image:
        name: splunk/splunk
        source: pull

    - name: Create a directory for the certificate
      file:
        path: /opt/splunk/certs
        state: directory
        mode: '0755'

    - name: Copy certificate to the server
      copy:
        src: /path/to/your/splunk_certificate.crt
        dest: /opt/splunk/certs/splunk_certificate.crt

    - name: Run Splunk container with mounted certificate
      docker_container:
        name: splunk
        image: splunk/splunk:latest
        state: started
        restart_policy: always
        ports:
          - "8000:8000"  # Web interface port
          - "8088:8088"  # HTTP Event Collector (HEC) port
        volumes:
          - /opt/splunk/certs:/opt/splunk/certs
            /home/ubuntu/splunkCert.pem:/opt/splunk/etc/auth/splunkCert.pem
        env:
          SPLUNK_START_ARGS: '--accept-license'
        command: /opt/splunk/bin/splunk start --accept-license

    - name: Ensure Splunk is running
      command: docker ps
      register: result

    - name: Debug output
      debug:
        msg: "{{ result.stdout }}"
